# Generated by Django 5.0.6 on 2024-05-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, 'PENDING'), (0, 'DONE')], default=1),
        ),
    ]
